# Generated by Django 4.2.30 on 2026-04-11 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebateSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for pitch'), ('active', 'Active debate'), ('completed', 'Debate completed')], default='waiting', max_length=20)),
                ('current_turn', models.IntegerField(default=0)),
                ('pitch_topic', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scorecard', models.JSONField(blank=True, null=True)),
                ('tavily_cache', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User (Founder)'), ('investor', 'Investor Persona'), ('customer', 'Customer Persona'), ('competitor', 'Competitor Persona'), ('system', 'System Message')], max_length=20)),
                ('content', models.TextField()),
                ('turn_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_entries', to='debate.debatesession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'turn_number'], name='debate_glob_session_2382a2_idx'), models.Index(fields=['session', 'role'], name='debate_glob_session_7d07cd_idx')],
            },
        ),
    ]
