# Generated by Django 4.2.30 on 2026-05-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_debatesession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatesession',
            name='deep_dive_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='debatesession',
            name='panel_turn_count',
            field=models.IntegerField(default=0),
        ),
    ]
